### ISSUE TITLE
Is this Android 4.4 compatible?

### ISSUE THREAD

**Issue by Roburetto** [gaz-github/droidbuddy#4]
Can you please clarify the minimum Android version the app should be able to connect with?
Thanks.

**Comment by gaz-github** [comment]
Hi there. Could you move this issue over to the new repository over at https://gitlab.com/gazlene/droidbuddy ? Thanks.

**Comment by Roburetto** [comment]
https://gitlab.com/gazlene/droidbuddy/-/issues/4
